apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost
  namespace: default
  labels:
    app: ghost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
